config/routes.rb
Rails.application.routes.draw do
  resources :categories

  devise_for :users
  resources :articles do
    resources :comments, only: [:create, :destroy, :update, :show]
  end
=begin
    get "/articles"  index
    post "/articles"  create
    delete "/articles"  delete
    get "/articles/:id"  show
    get "/articles/new"  new
    get "articles/:id/edit"  edit
    patch "/articles/:id"  update
    put "/articles/:id"  update
=end

  root 'welcome#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	# La tabla => articles
	# Campos => article.title() => 'El título Artículo'
	# Escribir métodos
	belongs_to :user
	has_many :comments
	validates :title, presence: true, uniqueness: true
	validates :body, presence: true, length: { minimum: 20 }
	before_save :set_visits_count
	#validates :username, format: { width: /regex/ }
	def update_visits_count
		self.save if self.visits_count.nil?
		self.update(visits_count: self.visits_count + 1)
	end
	private
	
	def set_visits_count
		self.visits_count ||= 0
	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates :name, presence: true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article
end

app/models/has_category.rb
class HasCategory < ActiveRecord::Base
  belongs_to :article
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :articles
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_categories

  private

  def set_categories
  	@categories = Category.all
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :authenticate_user!, except: [:show, :index]
	before_action :set_article, except: [:index, :new, :create]
	#GET /articles
	def index
		@articles = Article.all
	end

	#GET /articles/:id
	def show
		@article.update_visits_count
		@comment = Comment.new
	end

	#GET /article/new
	def new
		@article = Article.new
		@categories = Category.all
	end

	def edit
	end

	#POST /articles
	def create
		#@article = Article.new(title: params[:article][:title], body: params[:article][:body])
		#@article = Article.new(article_params)
		@article = current_user.articles.new(article_params)
		if @article.save
			redirect_to @article
		else
			render :new
		end
	end

	#DELETE /articles/:id
	def destroy
		#DELETE FROM articles
		@article.destroy # Destroy eliminar el objeto de la DB
		redirect_to articles_path
	end

	#PUT /articles/:id
	def update
		if @article.update(article_params)
			redirect_to @article
		else
			render :edir
		end
	end

	private

	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :body)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @categories = Category.all
    respond_with(@categories)
  end

  def show
    respond_with(@category)
  end

  def new
    @category = Category.new
    respond_with(@category)
  end

  def edit
  end

  def create
    @category = Category.new(category_params)
    @category.save
    respond_with(@category)
  end

  def update
    @category.update(category_params)
    respond_with(@category)
  end

  def destroy
    @category.destroy
    respond_with(@category)
  end

  private
    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :color)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:update, :destroy, :show]
  before_action :set_article
  before_action :authenticate_user!
  respond_to :html

  def show
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.article = @article
    #respond_with(@comment.article)
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.article, notice: 'Comment was successfully created.'}
        format.json { render :show, status: :created, location: @comment.article }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @comment.update(comment_params)
    respond_with(@comment.article)
  end

  def destroy
    @comment.destroy
    respond_with(@article)
  end

  private
    def set_article
      @article = Article.find(params[:article_id])
    end
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :article_id, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<% name ||= "Crear" %>
<h1><%= name %> artículo</h1>
<%= form_for(@article) do |f| %>
	<% @article.errors.full_messages.each do |message| %>
		<div class="be-red white top-space">
			* <%= message %>
		</div>
	<% end %>
	<div class="field">
		<%= f.text_field :title, placeholder: "Título", class: "form-control" %>
	</div>
	<div class="field">
		<%= f.text_area :body, placeholder: "Escribe aquí el artículo", style: "height:250px;", class:"form-control" %>
	</div>
	<div class="field">
		<label>Categorias</label>
		<% @categories.each do |category| %>
			<div class="field">
				<%= check_box_tag "categories[]", category.id %>  <%= category.name %>
			</div>
		<% end %>
	</div>
	<div class="field">
		<%= f.submit "Guardar", class: "btn be-red white" %>
	</div>
<% end %>

app/views/articles/edit.html.erb
<div style="width:80%; margin:0 auto;">
	<%= render "form", name: "Editar" %>
</div>

app/views/articles/index.html.erb
<a><%= link_to "Crear Articulo", new_article_path%></a><br>
<% @articles.each do |article| %>
	<h1><%= link_to article.title, article %></h1>
	<div>
		<%= article.body %> - <%= link_to "Eliminar", article, method: :delete, class: "red" %>
	</div>
<% end %>

app/views/articles/new.html.erb
<div style="width:80%; margin:0 auto;">
	<%= render "form", name: "Crear" %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<% unless @article.user.nil? %>
<p>
	Escrito por <%= @article.user.email %>
</p>
<p>
	Visitas: <%= @article.visits_count %>
</p>
<% end %>
<div>
	<%= @article.body %>
</div>
<div class="field">
	<h3>Comentarios</h3>
	<%= render "comments/form" %>
	<ul id="comments-box">
	  <% @article.comments.each do |comment| %>
	    <li>
	      <%= comment.body %> - <%= comment.user.email %>
	    </li>
	  <% end %>
	</ul>
</div>
<div>
	<%= link_to "Editar", edit_article_path(@article) %>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.color_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.color %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @category.color %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/comments/_form.html.erb
<%= form_for([@article,@comment], remote: true, html: { id: "comments-form", :"data-type" => "json" }) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user %></td>
        <td><%= comment.article %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Article:</strong>
  <%= @comment.article %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Blog de Andrés on Rails</title>
  <link rel="stylesheet" type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "partials/navigation" %>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

<%= yield %>
   

   <div id="footer" style="height: 60px; background-color: #f5f5f5; position:absolute; text-align:center; margin-top:40px;">

   <div id="footer" style="height: 60px; background-color: #f5f5f5; text-align:center;">
      <div class="container" style="width:auto; max-width:680px; padding:0 15px;">
        <p class="text-muted" style="margin: 20px,0;">Suport by <a><%= link_to "Andrés Frank Alexis", "https://www.facebook.com/andresfrankm" %></a> 
        </p> - <p><%= Time.new %></p>
      </div>
    </div>
</body>
</html>

app/views/partials/_navigation.html.erb
<header>
		<nav class="be-red white large-padding">
			<ul class="no-list row center-xs around-xs middle-xs">
				<li class="col-md">
					<h1 class="no-margin" id="logo"><%= link_to "Mousy blog", root_path %></h1>
				</li>
				<li class="col-md">
					<%= link_to "Inicio", root_path %>
				</li>
				<li class="col-md">
					<%= link_to "Articulos", articles_path %>
				</li>
				<% @categories.each do |category| %>
				<li class="col-md">
					<%= link_to category.name, category  %>
				</li>
				<% end %>
				<% if user_signed_in? %>
					<li class="col-md">
						<%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete %>
					</li>
				<% else %>
					<li class="col-md">
						<%= link_to "Iniciar Sesión", new_user_session_path %>
					</li>
					<li class="col-md">
						<%= link_to "Crear Cuenta", new_user_registration_path %>
					</li>
				<% end %>
			</ul>
		</nav>

	</header>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
	<h1>Bienvenido <%= current_user.email %></h1>
<% else %>
	<h1>Bienvenido a blog, REGISTRATE</h1>
<% end %>
<br>
<%= form_tag("http://www.unap.edu.pe/siu12/comedor/") %>
<%= label_tag "codigo Andres"%><br>
<%= text_field_tag "txt-codigo", "130950" %><br>
<%= label_tag "contraseña" %><br>
<%= password_field_tag "txt-clave", "50333766" %><br>
<%= submit_tag %><br>

<%= form_tag("http://www.unap.edu.pe/siu12/comedor/") %>
<%= label_tag "codigo Paola"%><br>
<%= text_field_tag "txt-codigo", "140947" %><br>
<%= label_tag "contraseña" %><br>
<%= password_field_tag "txt-clave", "d9cd2707" %><br>
<%= submit_tag %><br>

<%= form_tag("http://www.unap.edu.pe/siu12/comedor/") %>
<%= label_tag "codigo"%><br>
<%= text_field_tag "txt-codigo" %><br>
<%= label_tag "contraseña" %><br>
<%= password_field_tag "txt-clave" %><br>
<%= submit_tag %>